"""District model for Sierra Leone's administrative districts."""

from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean, Integer, Text, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship

from app.database import Base


class District(Base):
    """
    District represents a second-level administrative area within a Region.

    Each region can have up to 10 districts (codes 0-9).
    Districts are created manually by superadmins.
    District codes are auto-generated by the system (sequential within region).

    The combination of region_code + district_code forms the first 2 digits
    of the postal zone primary code.
    """

    __tablename__ = "districts"

    # Primary key: Auto-generated ID
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to region
    region_id = Column(Integer, ForeignKey("regions.id"), nullable=False, index=True)

    # System-assigned code (0-9 within region)
    code = Column(String(1), nullable=False)

    # Full code combining region and district (e.g., "WU", "NBO", "NWPL")
    full_code = Column(String(10), unique=True, nullable=False, index=True)

    # Human-defined fields
    name = Column(String(100), nullable=False)
    short_code = Column(String(5), nullable=False)  # e.g., "BO", "KEN", "FT"
    capital = Column(String(100), nullable=True)  # District capital/main town
    description = Column(Text, nullable=True)

    # Chiefdoms/Wards within the district (JSON array of names)
    chiefdoms = Column(JSONB, nullable=True, default=list)

    # Population estimate (optional metadata)
    population = Column(Integer, nullable=True)
    area_sq_km = Column(Integer, nullable=True)

    # Status
    is_active = Column(Boolean, default=True, nullable=False)
    is_locked = Column(Boolean, default=False, nullable=False)  # Locked after first zone created

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = Column(String(100), nullable=True)

    # Relationships
    region = relationship("Region", back_populates="districts")
    zones = relationship("Zone", back_populates="district", lazy="dynamic")

    def __repr__(self):
        return f"<District {self.full_code}: {self.name}>"

    @property
    def zone_count(self) -> int:
        """Get the number of zones in this district."""
        return self.zones.count()
