"""Region model for Sierra Leone's administrative regions."""

from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean, Integer, Text
from sqlalchemy.orm import relationship

from app.database import Base


class Region(Base):
    """
    Region represents a top-level administrative area in Sierra Leone.

    Sierra Leone has 5 regions:
    - Western Area (including Freetown)
    - North West Province
    - North East Province
    - Southern Province
    - Eastern Province

    Regions are created manually by superadmins.
    Region codes (1-5) are auto-generated by the system.
    """

    __tablename__ = "regions"

    # Primary key: Auto-generated ID
    id = Column(Integer, primary_key=True, autoincrement=True)

    # System-assigned code (1-5) - auto-incremented
    code = Column(String(2), unique=True, nullable=False, index=True)

    # Human-defined fields
    name = Column(String(100), unique=True, nullable=False)
    short_code = Column(String(5), unique=True, nullable=False)  # e.g., "WA", "NW", "NE", "S", "E"
    description = Column(Text, nullable=True)

    # Status
    is_active = Column(Boolean, default=True, nullable=False)
    is_locked = Column(Boolean, default=False, nullable=False)  # Locked after first district created

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = Column(String(100), nullable=True)

    # Relationships
    districts = relationship("District", back_populates="region", lazy="dynamic")

    def __repr__(self):
        return f"<Region {self.code}: {self.name}>"

    @property
    def district_count(self) -> int:
        """Get the number of districts in this region."""
        return self.districts.count()
