"""Zone model for geographic postal code areas."""

from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean, Integer, Text, ForeignKey
from sqlalchemy.orm import relationship
from geoalchemy2 import Geometry

from app.database import Base


class Zone(Base):
    """
    Zone represents a geographic postal code area within a District.

    Zone boundaries are drawn manually by admins on the map.
    Zone numbers (00-99) are auto-generated by the system.

    The primary postal code format is: XYZZ (New Zealand style, purely numeric)
    - X: Region code (1-5)
    - Y: District code (0-9)
    - ZZ: Zone number (00-99)

    Examples:
    - 1100 = Western Area Urban (Freetown CBD)
    - 1000 = Western Area Rural (Waterloo)
    - 2100 = Northern Province, Bombali District
    - 4100 = Southern Province, Bo District

    Full PDA-ID format: SL-XYZZ-NNN-NNNNNN-C
    - XYZZ: 4-digit postal code
    - NNN: 3-digit delivery segment
    - NNNNNN: 6-digit sequence number
    - C: Luhn check digit
    """

    __tablename__ = "zones"

    # Primary key: Auto-generated ID
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to district
    district_id = Column(Integer, ForeignKey("districts.id"), nullable=False, index=True)

    # System-assigned zone number (001-999 within district)
    zone_number = Column(String(3), nullable=False)

    # Full primary code (e.g., "WU-001", "NBO-015")
    primary_code = Column(String(15), unique=True, nullable=False, index=True)

    # Human-defined fields (optional name for the zone)
    name = Column(String(100), nullable=True)
    description = Column(Text, nullable=True)

    # Ward/Chiefdom this zone belongs to (for Freetown wards)
    ward = Column(String(50), nullable=True)

    # Geographic boundary (polygon drawn on map)
    geometry = Column(Geometry("POLYGON", srid=4326), nullable=True)

    # Center point for display
    center_lat = Column(String(20), nullable=True)
    center_lng = Column(String(20), nullable=True)

    # Zone type
    zone_type = Column(String(20), default="mixed")  # residential, commercial, industrial, mixed

    # Status
    is_active = Column(Boolean, default=True, nullable=False)
    is_locked = Column(Boolean, default=False, nullable=False)  # Locked after first address created

    # Sequence counter for segment/address generation
    next_segment = Column(Integer, default=1, nullable=False)
    address_count = Column(Integer, default=0, nullable=False)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = Column(String(100), nullable=True)

    # Relationships
    district = relationship("District", back_populates="zones")

    def __repr__(self):
        return f"<Zone {self.primary_code}: {self.name or 'Unnamed'}>"

    def get_full_postal_code(self, segment: str) -> str:
        """Generate full postal code with segment."""
        return f"{self.primary_code}-{segment}"
